# Generated by Django 3.1.8 on 2022-08-17 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0009_alter_fcmdevice_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firebase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyDevice',
            new_name='myModel',
        ),
    ]
